baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Conglomerate'
theme = 'blowfish'

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    name = "Members"
    url = "/members/"
    weight = 3

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4

  [[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 5

  [[menu.main]]
    name = "Join Us"
    url = "/join/"
    weight = 6

[markup] #to avoid '#' signs showing up on the website
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  defaultAppearance = "dark"
  autoSwitchAppearance = false
  logo = "logo.png"
  copyright = "© 2026 Reihaneh Hosseini <br> Last updated: May 2026"

[params.homepage]
  layout = "background"
  homepageImage = "!group.JPG"

[params.author]
name = "COnGloMERaTE"
image = "logo.png"
headline = "COmputatinal Granular MEchanics Research TEam"

[params.header]
  layout = "fixed"

[params.article]
  showDate = false
  showViews = false
  showLikes = false
  showAuthor = false
  showAuthorsBadges = false
  showReadingTime = false
  showWordCount = false
  showTaxonomies = false
  showEdit = false
  showComments = false
  showSharingLinks = false

