baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Conglomerate'
theme = 'blowfish'

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    name = "People"
    url = "/people/"
    weight = 3

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4

  [[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 5

  [[menu.main]]
    name = "Join Us"
    url = "/join/"
    weight = 6
